// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "gonews/save_service/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockNewsStorage is an autogenerated mock type for the NewsStorage type
type MockNewsStorage struct {
	mock.Mock
}

type MockNewsStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNewsStorage) EXPECT() *MockNewsStorage_Expecter {
	return &MockNewsStorage_Expecter{mock: &_m.Mock}
}

// AddFavourite provides a mock function with given fields: ctx, userID, newsID
func (_m *MockNewsStorage) AddFavourite(ctx context.Context, userID uint64, newsID uint64) error {
	ret := _m.Called(ctx, userID, newsID)

	if len(ret) == 0 {
		panic("no return value specified for AddFavourite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) error); ok {
		r0 = rf(ctx, userID, newsID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNewsStorage_AddFavourite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFavourite'
type MockNewsStorage_AddFavourite_Call struct {
	*mock.Call
}

// AddFavourite is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - newsID uint64
func (_e *MockNewsStorage_Expecter) AddFavourite(ctx interface{}, userID interface{}, newsID interface{}) *MockNewsStorage_AddFavourite_Call {
	return &MockNewsStorage_AddFavourite_Call{Call: _e.mock.On("AddFavourite", ctx, userID, newsID)}
}

func (_c *MockNewsStorage_AddFavourite_Call) Run(run func(ctx context.Context, userID uint64, newsID uint64)) *MockNewsStorage_AddFavourite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64))
	})
	return _c
}

func (_c *MockNewsStorage_AddFavourite_Call) Return(_a0 error) *MockNewsStorage_AddFavourite_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNewsStorage_AddFavourite_Call) RunAndReturn(run func(context.Context, uint64, uint64) error) *MockNewsStorage_AddFavourite_Call {
	_c.Call.Return(run)
	return _c
}

// AddToSearchHistory provides a mock function with given fields: ctx, userID, query, results
func (_m *MockNewsStorage) AddToSearchHistory(ctx context.Context, userID uint64, query string, results []uint64) error {
	ret := _m.Called(ctx, userID, query, results)

	if len(ret) == 0 {
		panic("no return value specified for AddToSearchHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, string, []uint64) error); ok {
		r0 = rf(ctx, userID, query, results)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNewsStorage_AddToSearchHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToSearchHistory'
type MockNewsStorage_AddToSearchHistory_Call struct {
	*mock.Call
}

// AddToSearchHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - query string
//   - results []uint64
func (_e *MockNewsStorage_Expecter) AddToSearchHistory(ctx interface{}, userID interface{}, query interface{}, results interface{}) *MockNewsStorage_AddToSearchHistory_Call {
	return &MockNewsStorage_AddToSearchHistory_Call{Call: _e.mock.On("AddToSearchHistory", ctx, userID, query, results)}
}

func (_c *MockNewsStorage_AddToSearchHistory_Call) Run(run func(ctx context.Context, userID uint64, query string, results []uint64)) *MockNewsStorage_AddToSearchHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(string), args[3].([]uint64))
	})
	return _c
}

func (_c *MockNewsStorage_AddToSearchHistory_Call) Return(_a0 error) *MockNewsStorage_AddToSearchHistory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNewsStorage_AddToSearchHistory_Call) RunAndReturn(run func(context.Context, uint64, string, []uint64) error) *MockNewsStorage_AddToSearchHistory_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, name
func (_m *MockNewsStorage) CreateUser(ctx context.Context, name string) (uint64, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uint64, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uint64); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNewsStorage_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockNewsStorage_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockNewsStorage_Expecter) CreateUser(ctx interface{}, name interface{}) *MockNewsStorage_CreateUser_Call {
	return &MockNewsStorage_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, name)}
}

func (_c *MockNewsStorage_CreateUser_Call) Run(run func(ctx context.Context, name string)) *MockNewsStorage_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockNewsStorage_CreateUser_Call) Return(_a0 uint64, _a1 error) *MockNewsStorage_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNewsStorage_CreateUser_Call) RunAndReturn(run func(context.Context, string) (uint64, error)) *MockNewsStorage_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetFavourites provides a mock function with given fields: ctx, userID
func (_m *MockNewsStorage) GetFavourites(ctx context.Context, userID uint64) ([]*models.News, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFavourites")
	}

	var r0 []*models.News
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]*models.News, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []*models.News); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.News)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNewsStorage_GetFavourites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFavourites'
type MockNewsStorage_GetFavourites_Call struct {
	*mock.Call
}

// GetFavourites is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockNewsStorage_Expecter) GetFavourites(ctx interface{}, userID interface{}) *MockNewsStorage_GetFavourites_Call {
	return &MockNewsStorage_GetFavourites_Call{Call: _e.mock.On("GetFavourites", ctx, userID)}
}

func (_c *MockNewsStorage_GetFavourites_Call) Run(run func(ctx context.Context, userID uint64)) *MockNewsStorage_GetFavourites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockNewsStorage_GetFavourites_Call) Return(_a0 []*models.News, _a1 error) *MockNewsStorage_GetFavourites_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNewsStorage_GetFavourites_Call) RunAndReturn(run func(context.Context, uint64) ([]*models.News, error)) *MockNewsStorage_GetFavourites_Call {
	_c.Call.Return(run)
	return _c
}

// GetNewsByIDs provides a mock function with given fields: ctx, IDs
func (_m *MockNewsStorage) GetNewsByIDs(ctx context.Context, IDs []uint64) ([]*models.News, error) {
	ret := _m.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for GetNewsByIDs")
	}

	var r0 []*models.News
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) ([]*models.News, error)); ok {
		return rf(ctx, IDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) []*models.News); ok {
		r0 = rf(ctx, IDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.News)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint64) error); ok {
		r1 = rf(ctx, IDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNewsStorage_GetNewsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNewsByIDs'
type MockNewsStorage_GetNewsByIDs_Call struct {
	*mock.Call
}

// GetNewsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uint64
func (_e *MockNewsStorage_Expecter) GetNewsByIDs(ctx interface{}, IDs interface{}) *MockNewsStorage_GetNewsByIDs_Call {
	return &MockNewsStorage_GetNewsByIDs_Call{Call: _e.mock.On("GetNewsByIDs", ctx, IDs)}
}

func (_c *MockNewsStorage_GetNewsByIDs_Call) Run(run func(ctx context.Context, IDs []uint64)) *MockNewsStorage_GetNewsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint64))
	})
	return _c
}

func (_c *MockNewsStorage_GetNewsByIDs_Call) Return(_a0 []*models.News, _a1 error) *MockNewsStorage_GetNewsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNewsStorage_GetNewsByIDs_Call) RunAndReturn(run func(context.Context, []uint64) ([]*models.News, error)) *MockNewsStorage_GetNewsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetSearchHistory provides a mock function with given fields: ctx, userID
func (_m *MockNewsStorage) GetSearchHistory(ctx context.Context, userID uint64) ([]string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSearchHistory")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []string); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNewsStorage_GetSearchHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSearchHistory'
type MockNewsStorage_GetSearchHistory_Call struct {
	*mock.Call
}

// GetSearchHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockNewsStorage_Expecter) GetSearchHistory(ctx interface{}, userID interface{}) *MockNewsStorage_GetSearchHistory_Call {
	return &MockNewsStorage_GetSearchHistory_Call{Call: _e.mock.On("GetSearchHistory", ctx, userID)}
}

func (_c *MockNewsStorage_GetSearchHistory_Call) Run(run func(ctx context.Context, userID uint64)) *MockNewsStorage_GetSearchHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockNewsStorage_GetSearchHistory_Call) Return(_a0 []string, _a1 error) *MockNewsStorage_GetSearchHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNewsStorage_GetSearchHistory_Call) RunAndReturn(run func(context.Context, uint64) ([]string, error)) *MockNewsStorage_GetSearchHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptions provides a mock function with given fields: ctx
func (_m *MockNewsStorage) GetSubscriptions(ctx context.Context) ([]*models.Subscription, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptions")
	}

	var r0 []*models.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Subscription, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Subscription); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNewsStorage_GetSubscriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptions'
type MockNewsStorage_GetSubscriptions_Call struct {
	*mock.Call
}

// GetSubscriptions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockNewsStorage_Expecter) GetSubscriptions(ctx interface{}) *MockNewsStorage_GetSubscriptions_Call {
	return &MockNewsStorage_GetSubscriptions_Call{Call: _e.mock.On("GetSubscriptions", ctx)}
}

func (_c *MockNewsStorage_GetSubscriptions_Call) Run(run func(ctx context.Context)) *MockNewsStorage_GetSubscriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockNewsStorage_GetSubscriptions_Call) Return(_a0 []*models.Subscription, _a1 error) *MockNewsStorage_GetSubscriptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNewsStorage_GetSubscriptions_Call) RunAndReturn(run func(context.Context) ([]*models.Subscription, error)) *MockNewsStorage_GetSubscriptions_Call {
	_c.Call.Return(run)
	return _c
}

// MarkNewsAsSeen provides a mock function with given fields: ctx, userID, newsID
func (_m *MockNewsStorage) MarkNewsAsSeen(ctx context.Context, userID uint64, newsID uint64) error {
	ret := _m.Called(ctx, userID, newsID)

	if len(ret) == 0 {
		panic("no return value specified for MarkNewsAsSeen")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) error); ok {
		r0 = rf(ctx, userID, newsID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNewsStorage_MarkNewsAsSeen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkNewsAsSeen'
type MockNewsStorage_MarkNewsAsSeen_Call struct {
	*mock.Call
}

// MarkNewsAsSeen is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - newsID uint64
func (_e *MockNewsStorage_Expecter) MarkNewsAsSeen(ctx interface{}, userID interface{}, newsID interface{}) *MockNewsStorage_MarkNewsAsSeen_Call {
	return &MockNewsStorage_MarkNewsAsSeen_Call{Call: _e.mock.On("MarkNewsAsSeen", ctx, userID, newsID)}
}

func (_c *MockNewsStorage_MarkNewsAsSeen_Call) Run(run func(ctx context.Context, userID uint64, newsID uint64)) *MockNewsStorage_MarkNewsAsSeen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64))
	})
	return _c
}

func (_c *MockNewsStorage_MarkNewsAsSeen_Call) Return(_a0 error) *MockNewsStorage_MarkNewsAsSeen_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNewsStorage_MarkNewsAsSeen_Call) RunAndReturn(run func(context.Context, uint64, uint64) error) *MockNewsStorage_MarkNewsAsSeen_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: ctx, userID, keyword
func (_m *MockNewsStorage) Subscribe(ctx context.Context, userID uint64, keyword string) error {
	ret := _m.Called(ctx, userID, keyword)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, string) error); ok {
		r0 = rf(ctx, userID, keyword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNewsStorage_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockNewsStorage_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - keyword string
func (_e *MockNewsStorage_Expecter) Subscribe(ctx interface{}, userID interface{}, keyword interface{}) *MockNewsStorage_Subscribe_Call {
	return &MockNewsStorage_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, userID, keyword)}
}

func (_c *MockNewsStorage_Subscribe_Call) Run(run func(ctx context.Context, userID uint64, keyword string)) *MockNewsStorage_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(string))
	})
	return _c
}

func (_c *MockNewsStorage_Subscribe_Call) Return(_a0 error) *MockNewsStorage_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNewsStorage_Subscribe_Call) RunAndReturn(run func(context.Context, uint64, string) error) *MockNewsStorage_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertNews provides a mock function with given fields: ctx, news
func (_m *MockNewsStorage) UpsertNews(ctx context.Context, news []*models.News) error {
	ret := _m.Called(ctx, news)

	if len(ret) == 0 {
		panic("no return value specified for UpsertNews")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*models.News) error); ok {
		r0 = rf(ctx, news)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNewsStorage_UpsertNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertNews'
type MockNewsStorage_UpsertNews_Call struct {
	*mock.Call
}

// UpsertNews is a helper method to define mock.On call
//   - ctx context.Context
//   - news []*models.News
func (_e *MockNewsStorage_Expecter) UpsertNews(ctx interface{}, news interface{}) *MockNewsStorage_UpsertNews_Call {
	return &MockNewsStorage_UpsertNews_Call{Call: _e.mock.On("UpsertNews", ctx, news)}
}

func (_c *MockNewsStorage_UpsertNews_Call) Run(run func(ctx context.Context, news []*models.News)) *MockNewsStorage_UpsertNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*models.News))
	})
	return _c
}

func (_c *MockNewsStorage_UpsertNews_Call) Return(_a0 error) *MockNewsStorage_UpsertNews_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNewsStorage_UpsertNews_Call) RunAndReturn(run func(context.Context, []*models.News) error) *MockNewsStorage_UpsertNews_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNewsStorage creates a new instance of MockNewsStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNewsStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNewsStorage {
	mock := &MockNewsStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
