// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: news_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common Messages
type News struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,8,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *News) Reset() {
	*x = News{}
	mi := &file_news_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *News) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*News) ProtoMessage() {}

func (x *News) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use News.ProtoReflect.Descriptor instead.
func (*News) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{0}
}

func (x *News) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *News) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *News) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *News) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *News) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *News) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *News) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *News) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_news_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_news_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type SaveNewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	News          []*News                `protobuf:"bytes,1,rep,name=news,proto3" json:"news,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveNewsRequest) Reset() {
	*x = SaveNewsRequest{}
	mi := &file_news_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveNewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveNewsRequest) ProtoMessage() {}

func (x *SaveNewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveNewsRequest.ProtoReflect.Descriptor instead.
func (*SaveNewsRequest) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{3}
}

func (x *SaveNewsRequest) GetNews() []*News {
	if x != nil {
		return x.News
	}
	return nil
}

type SaveNewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveNewsResponse) Reset() {
	*x = SaveNewsResponse{}
	mi := &file_news_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveNewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveNewsResponse) ProtoMessage() {}

func (x *SaveNewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveNewsResponse.ProtoReflect.Descriptor instead.
func (*SaveNewsResponse) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{4}
}

func (x *SaveNewsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetNewsByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewsByIDsRequest) Reset() {
	*x = GetNewsByIDsRequest{}
	mi := &file_news_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewsByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewsByIDsRequest) ProtoMessage() {}

func (x *GetNewsByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewsByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetNewsByIDsRequest) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetNewsByIDsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetNewsByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	News          []*News                `protobuf:"bytes,1,rep,name=news,proto3" json:"news,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewsByIDsResponse) Reset() {
	*x = GetNewsByIDsResponse{}
	mi := &file_news_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewsByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewsByIDsResponse) ProtoMessage() {}

func (x *GetNewsByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewsByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetNewsByIDsResponse) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetNewsByIDsResponse) GetNews() []*News {
	if x != nil {
		return x.News
	}
	return nil
}

type AddFavouriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewsId        uint64                 `protobuf:"varint,2,opt,name=news_id,json=newsId,proto3" json:"news_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFavouriteRequest) Reset() {
	*x = AddFavouriteRequest{}
	mi := &file_news_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFavouriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavouriteRequest) ProtoMessage() {}

func (x *AddFavouriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavouriteRequest.ProtoReflect.Descriptor instead.
func (*AddFavouriteRequest) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{7}
}

func (x *AddFavouriteRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddFavouriteRequest) GetNewsId() uint64 {
	if x != nil {
		return x.NewsId
	}
	return 0
}

type AddFavouriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFavouriteResponse) Reset() {
	*x = AddFavouriteResponse{}
	mi := &file_news_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFavouriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavouriteResponse) ProtoMessage() {}

func (x *AddFavouriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavouriteResponse.ProtoReflect.Descriptor instead.
func (*AddFavouriteResponse) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{8}
}

func (x *AddFavouriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetFavouritesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFavouritesRequest) Reset() {
	*x = GetFavouritesRequest{}
	mi := &file_news_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFavouritesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavouritesRequest) ProtoMessage() {}

func (x *GetFavouritesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavouritesRequest.ProtoReflect.Descriptor instead.
func (*GetFavouritesRequest) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetFavouritesRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetFavouritesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	News          []*News                `protobuf:"bytes,1,rep,name=news,proto3" json:"news,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFavouritesResponse) Reset() {
	*x = GetFavouritesResponse{}
	mi := &file_news_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFavouritesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavouritesResponse) ProtoMessage() {}

func (x *GetFavouritesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavouritesResponse.ProtoReflect.Descriptor instead.
func (*GetFavouritesResponse) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetFavouritesResponse) GetNews() []*News {
	if x != nil {
		return x.News
	}
	return nil
}

type AddToSearchHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Results       []uint64               `protobuf:"varint,3,rep,packed,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToSearchHistoryRequest) Reset() {
	*x = AddToSearchHistoryRequest{}
	mi := &file_news_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToSearchHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToSearchHistoryRequest) ProtoMessage() {}

func (x *AddToSearchHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToSearchHistoryRequest.ProtoReflect.Descriptor instead.
func (*AddToSearchHistoryRequest) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{11}
}

func (x *AddToSearchHistoryRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddToSearchHistoryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AddToSearchHistoryRequest) GetResults() []uint64 {
	if x != nil {
		return x.Results
	}
	return nil
}

type AddToSearchHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToSearchHistoryResponse) Reset() {
	*x = AddToSearchHistoryResponse{}
	mi := &file_news_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToSearchHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToSearchHistoryResponse) ProtoMessage() {}

func (x *AddToSearchHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToSearchHistoryResponse.ProtoReflect.Descriptor instead.
func (*AddToSearchHistoryResponse) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{12}
}

func (x *AddToSearchHistoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetSearchHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSearchHistoryRequest) Reset() {
	*x = GetSearchHistoryRequest{}
	mi := &file_news_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSearchHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSearchHistoryRequest) ProtoMessage() {}

func (x *GetSearchHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSearchHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetSearchHistoryRequest) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetSearchHistoryRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetSearchHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queries       []string               `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSearchHistoryResponse) Reset() {
	*x = GetSearchHistoryResponse{}
	mi := &file_news_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSearchHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSearchHistoryResponse) ProtoMessage() {}

func (x *GetSearchHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSearchHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetSearchHistoryResponse) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetSearchHistoryResponse) GetQueries() []string {
	if x != nil {
		return x.Queries
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_news_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{15}
}

func (x *SubscribeRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubscribeRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_news_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{16}
}

func (x *SubscribeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionsRequest) Reset() {
	*x = GetSubscriptionsRequest{}
	mi := &file_news_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionsRequest) ProtoMessage() {}

func (x *GetSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{17}
}

type GetSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionsResponse) Reset() {
	*x = GetSubscriptionsResponse{}
	mi := &file_news_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionsResponse) ProtoMessage() {}

func (x *GetSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_news_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{19}
}

func (x *Subscription) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Subscription) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Subscription) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

// Search Service Messages
type SearchNewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Sources       *string                `protobuf:"bytes,3,opt,name=sources,proto3,oneof" json:"sources,omitempty"`
	Domains       *string                `protobuf:"bytes,4,opt,name=domains,proto3,oneof" json:"domains,omitempty"`
	From          *string                `protobuf:"bytes,5,opt,name=from,proto3,oneof" json:"from,omitempty"`
	To            *string                `protobuf:"bytes,6,opt,name=to,proto3,oneof" json:"to,omitempty"`
	Language      *string                `protobuf:"bytes,7,opt,name=language,proto3,oneof" json:"language,omitempty"`
	SortBy        *string                `protobuf:"bytes,8,opt,name=sort_by,json=sortBy,proto3,oneof" json:"sort_by,omitempty"`
	PageSize      *int32                 `protobuf:"varint,9,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	Page          *int32                 `protobuf:"varint,10,opt,name=page,proto3,oneof" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchNewsRequest) Reset() {
	*x = SearchNewsRequest{}
	mi := &file_news_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchNewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchNewsRequest) ProtoMessage() {}

func (x *SearchNewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchNewsRequest.ProtoReflect.Descriptor instead.
func (*SearchNewsRequest) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{20}
}

func (x *SearchNewsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SearchNewsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchNewsRequest) GetSources() string {
	if x != nil && x.Sources != nil {
		return *x.Sources
	}
	return ""
}

func (x *SearchNewsRequest) GetDomains() string {
	if x != nil && x.Domains != nil {
		return *x.Domains
	}
	return ""
}

func (x *SearchNewsRequest) GetFrom() string {
	if x != nil && x.From != nil {
		return *x.From
	}
	return ""
}

func (x *SearchNewsRequest) GetTo() string {
	if x != nil && x.To != nil {
		return *x.To
	}
	return ""
}

func (x *SearchNewsRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *SearchNewsRequest) GetSortBy() string {
	if x != nil && x.SortBy != nil {
		return *x.SortBy
	}
	return ""
}

func (x *SearchNewsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *SearchNewsRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

type SearchNewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	News          []*News                `protobuf:"bytes,1,rep,name=news,proto3" json:"news,omitempty"`
	TotalResults  int32                  `protobuf:"varint,2,opt,name=total_results,json=totalResults,proto3" json:"total_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchNewsResponse) Reset() {
	*x = SearchNewsResponse{}
	mi := &file_news_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchNewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchNewsResponse) ProtoMessage() {}

func (x *SearchNewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchNewsResponse.ProtoReflect.Descriptor instead.
func (*SearchNewsResponse) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{21}
}

func (x *SearchNewsResponse) GetNews() []*News {
	if x != nil {
		return x.News
	}
	return nil
}

func (x *SearchNewsResponse) GetTotalResults() int32 {
	if x != nil {
		return x.TotalResults
	}
	return 0
}

type GetTopHeadlinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Country       *string                `protobuf:"bytes,2,opt,name=country,proto3,oneof" json:"country,omitempty"`
	Category      *string                `protobuf:"bytes,3,opt,name=category,proto3,oneof" json:"category,omitempty"`
	Sources       *string                `protobuf:"bytes,4,opt,name=sources,proto3,oneof" json:"sources,omitempty"`
	Query         *string                `protobuf:"bytes,5,opt,name=query,proto3,oneof" json:"query,omitempty"`
	PageSize      *int32                 `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	Page          *int32                 `protobuf:"varint,7,opt,name=page,proto3,oneof" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopHeadlinesRequest) Reset() {
	*x = GetTopHeadlinesRequest{}
	mi := &file_news_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopHeadlinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopHeadlinesRequest) ProtoMessage() {}

func (x *GetTopHeadlinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopHeadlinesRequest.ProtoReflect.Descriptor instead.
func (*GetTopHeadlinesRequest) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetTopHeadlinesRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetTopHeadlinesRequest) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *GetTopHeadlinesRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *GetTopHeadlinesRequest) GetSources() string {
	if x != nil && x.Sources != nil {
		return *x.Sources
	}
	return ""
}

func (x *GetTopHeadlinesRequest) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

func (x *GetTopHeadlinesRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *GetTopHeadlinesRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

type GetTopHeadlinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	News          []*News                `protobuf:"bytes,1,rep,name=news,proto3" json:"news,omitempty"`
	TotalResults  int32                  `protobuf:"varint,2,opt,name=total_results,json=totalResults,proto3" json:"total_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopHeadlinesResponse) Reset() {
	*x = GetTopHeadlinesResponse{}
	mi := &file_news_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopHeadlinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopHeadlinesResponse) ProtoMessage() {}

func (x *GetTopHeadlinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopHeadlinesResponse.ProtoReflect.Descriptor instead.
func (*GetTopHeadlinesResponse) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{23}
}

func (x *GetTopHeadlinesResponse) GetNews() []*News {
	if x != nil {
		return x.News
	}
	return nil
}

func (x *GetTopHeadlinesResponse) GetTotalResults() int32 {
	if x != nil {
		return x.TotalResults
	}
	return 0
}

type CheckNewArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	LastCheckTime string                 `protobuf:"bytes,2,opt,name=last_check_time,json=lastCheckTime,proto3" json:"last_check_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckNewArticlesRequest) Reset() {
	*x = CheckNewArticlesRequest{}
	mi := &file_news_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckNewArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckNewArticlesRequest) ProtoMessage() {}

func (x *CheckNewArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckNewArticlesRequest.ProtoReflect.Descriptor instead.
func (*CheckNewArticlesRequest) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{24}
}

func (x *CheckNewArticlesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *CheckNewArticlesRequest) GetLastCheckTime() string {
	if x != nil {
		return x.LastCheckTime
	}
	return ""
}

type CheckNewArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewArticles   []*News                `protobuf:"bytes,1,rep,name=new_articles,json=newArticles,proto3" json:"new_articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckNewArticlesResponse) Reset() {
	*x = CheckNewArticlesResponse{}
	mi := &file_news_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckNewArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckNewArticlesResponse) ProtoMessage() {}

func (x *CheckNewArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckNewArticlesResponse.ProtoReflect.Descriptor instead.
func (*CheckNewArticlesResponse) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{25}
}

func (x *CheckNewArticlesResponse) GetNewArticles() []*News {
	if x != nil {
		return x.NewArticles
	}
	return nil
}

// Notification Service Messages
type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Articles      []*News                `protobuf:"bytes,3,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_news_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{26}
}

func (x *SendNotificationRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SendNotificationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendNotificationRequest) GetArticles() []*News {
	if x != nil {
		return x.Articles
	}
	return nil
}

type SendNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_news_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_news_service_proto_rawDescGZIP(), []int{27}
}

func (x *SendNotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_news_service_proto protoreflect.FileDescriptor

const file_news_service_proto_rawDesc = "" +
	"\n" +
	"\x12news_service.proto\x12\x04news\"\xd0\x01\n" +
	"\x04News\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\x12!\n" +
	"\fpublished_at\x18\b \x01(\tR\vpublishedAt\"'\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"-\n" +
	"\x12CreateUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"1\n" +
	"\x0fSaveNewsRequest\x12\x1e\n" +
	"\x04news\x18\x01 \x03(\v2\n" +
	".news.NewsR\x04news\",\n" +
	"\x10SaveNewsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"'\n" +
	"\x13GetNewsByIDsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\"6\n" +
	"\x14GetNewsByIDsResponse\x12\x1e\n" +
	"\x04news\x18\x01 \x03(\v2\n" +
	".news.NewsR\x04news\"G\n" +
	"\x13AddFavouriteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x17\n" +
	"\anews_id\x18\x02 \x01(\x04R\x06newsId\"0\n" +
	"\x14AddFavouriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x14GetFavouritesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"7\n" +
	"\x15GetFavouritesResponse\x12\x1e\n" +
	"\x04news\x18\x01 \x03(\v2\n" +
	".news.NewsR\x04news\"d\n" +
	"\x19AddToSearchHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x18\n" +
	"\aresults\x18\x03 \x03(\x04R\aresults\"6\n" +
	"\x1aAddToSearchHistoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x17GetSearchHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"4\n" +
	"\x18GetSearchHistoryResponse\x12\x18\n" +
	"\aqueries\x18\x01 \x03(\tR\aqueries\"E\n" +
	"\x10SubscribeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\"-\n" +
	"\x11SubscribeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x19\n" +
	"\x17GetSubscriptionsRequest\"T\n" +
	"\x18GetSubscriptionsResponse\x128\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x12.news.SubscriptionR\rsubscriptions\"Q\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\"\x80\x03\n" +
	"\x11SearchNewsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x1d\n" +
	"\asources\x18\x03 \x01(\tH\x00R\asources\x88\x01\x01\x12\x1d\n" +
	"\adomains\x18\x04 \x01(\tH\x01R\adomains\x88\x01\x01\x12\x17\n" +
	"\x04from\x18\x05 \x01(\tH\x02R\x04from\x88\x01\x01\x12\x13\n" +
	"\x02to\x18\x06 \x01(\tH\x03R\x02to\x88\x01\x01\x12\x1f\n" +
	"\blanguage\x18\a \x01(\tH\x04R\blanguage\x88\x01\x01\x12\x1c\n" +
	"\asort_by\x18\b \x01(\tH\x05R\x06sortBy\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\t \x01(\x05H\x06R\bpageSize\x88\x01\x01\x12\x17\n" +
	"\x04page\x18\n" +
	" \x01(\x05H\aR\x04page\x88\x01\x01B\n" +
	"\n" +
	"\b_sourcesB\n" +
	"\n" +
	"\b_domainsB\a\n" +
	"\x05_fromB\x05\n" +
	"\x03_toB\v\n" +
	"\t_languageB\n" +
	"\n" +
	"\b_sort_byB\f\n" +
	"\n" +
	"_page_sizeB\a\n" +
	"\x05_page\"Y\n" +
	"\x12SearchNewsResponse\x12\x1e\n" +
	"\x04news\x18\x01 \x03(\v2\n" +
	".news.NewsR\x04news\x12#\n" +
	"\rtotal_results\x18\x02 \x01(\x05R\ftotalResults\"\xac\x02\n" +
	"\x16GetTopHeadlinesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1d\n" +
	"\acountry\x18\x02 \x01(\tH\x00R\acountry\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\x03 \x01(\tH\x01R\bcategory\x88\x01\x01\x12\x1d\n" +
	"\asources\x18\x04 \x01(\tH\x02R\asources\x88\x01\x01\x12\x19\n" +
	"\x05query\x18\x05 \x01(\tH\x03R\x05query\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x06 \x01(\x05H\x04R\bpageSize\x88\x01\x01\x12\x17\n" +
	"\x04page\x18\a \x01(\x05H\x05R\x04page\x88\x01\x01B\n" +
	"\n" +
	"\b_countryB\v\n" +
	"\t_categoryB\n" +
	"\n" +
	"\b_sourcesB\b\n" +
	"\x06_queryB\f\n" +
	"\n" +
	"_page_sizeB\a\n" +
	"\x05_page\"^\n" +
	"\x17GetTopHeadlinesResponse\x12\x1e\n" +
	"\x04news\x18\x01 \x03(\v2\n" +
	".news.NewsR\x04news\x12#\n" +
	"\rtotal_results\x18\x02 \x01(\x05R\ftotalResults\"[\n" +
	"\x17CheckNewArticlesRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12&\n" +
	"\x0flast_check_time\x18\x02 \x01(\tR\rlastCheckTime\"I\n" +
	"\x18CheckNewArticlesResponse\x12-\n" +
	"\fnew_articles\x18\x01 \x03(\v2\n" +
	".news.NewsR\vnewArticles\"t\n" +
	"\x17SendNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\barticles\x18\x03 \x03(\v2\n" +
	".news.NewsR\barticles\"4\n" +
	"\x18SendNotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xb0\x05\n" +
	"\vSaveService\x12A\n" +
	"\n" +
	"CreateUser\x12\x17.news.CreateUserRequest\x1a\x18.news.CreateUserResponse\"\x00\x12;\n" +
	"\bSaveNews\x12\x15.news.SaveNewsRequest\x1a\x16.news.SaveNewsResponse\"\x00\x12G\n" +
	"\fGetNewsByIDs\x12\x19.news.GetNewsByIDsRequest\x1a\x1a.news.GetNewsByIDsResponse\"\x00\x12G\n" +
	"\fAddFavourite\x12\x19.news.AddFavouriteRequest\x1a\x1a.news.AddFavouriteResponse\"\x00\x12J\n" +
	"\rGetFavourites\x12\x1a.news.GetFavouritesRequest\x1a\x1b.news.GetFavouritesResponse\"\x00\x12Y\n" +
	"\x12AddToSearchHistory\x12\x1f.news.AddToSearchHistoryRequest\x1a .news.AddToSearchHistoryResponse\"\x00\x12S\n" +
	"\x10GetSearchHistory\x12\x1d.news.GetSearchHistoryRequest\x1a\x1e.news.GetSearchHistoryResponse\"\x00\x12>\n" +
	"\tSubscribe\x12\x16.news.SubscribeRequest\x1a\x17.news.SubscribeResponse\"\x00\x12S\n" +
	"\x10GetSubscriptions\x12\x1d.news.GetSubscriptionsRequest\x1a\x1e.news.GetSubscriptionsResponse\"\x002\xf9\x01\n" +
	"\rSearchService\x12A\n" +
	"\n" +
	"SearchNews\x12\x17.news.SearchNewsRequest\x1a\x18.news.SearchNewsResponse\"\x00\x12P\n" +
	"\x0fGetTopHeadlines\x12\x1c.news.GetTopHeadlinesRequest\x1a\x1d.news.GetTopHeadlinesResponse\"\x00\x12S\n" +
	"\x10CheckNewArticles\x12\x1d.news.CheckNewArticlesRequest\x1a\x1e.news.CheckNewArticlesResponse\"\x002j\n" +
	"\x13NotificationService\x12S\n" +
	"\x10SendNotification\x12\x1d.news.SendNotificationRequest\x1a\x1e.news.SendNotificationResponse\"\x00B\x14Z\x12gonews/internal/pbb\x06proto3"

var (
	file_news_service_proto_rawDescOnce sync.Once
	file_news_service_proto_rawDescData []byte
)

func file_news_service_proto_rawDescGZIP() []byte {
	file_news_service_proto_rawDescOnce.Do(func() {
		file_news_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_news_service_proto_rawDesc), len(file_news_service_proto_rawDesc)))
	})
	return file_news_service_proto_rawDescData
}

var file_news_service_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_news_service_proto_goTypes = []any{
	(*News)(nil),                       // 0: news.News
	(*CreateUserRequest)(nil),          // 1: news.CreateUserRequest
	(*CreateUserResponse)(nil),         // 2: news.CreateUserResponse
	(*SaveNewsRequest)(nil),            // 3: news.SaveNewsRequest
	(*SaveNewsResponse)(nil),           // 4: news.SaveNewsResponse
	(*GetNewsByIDsRequest)(nil),        // 5: news.GetNewsByIDsRequest
	(*GetNewsByIDsResponse)(nil),       // 6: news.GetNewsByIDsResponse
	(*AddFavouriteRequest)(nil),        // 7: news.AddFavouriteRequest
	(*AddFavouriteResponse)(nil),       // 8: news.AddFavouriteResponse
	(*GetFavouritesRequest)(nil),       // 9: news.GetFavouritesRequest
	(*GetFavouritesResponse)(nil),      // 10: news.GetFavouritesResponse
	(*AddToSearchHistoryRequest)(nil),  // 11: news.AddToSearchHistoryRequest
	(*AddToSearchHistoryResponse)(nil), // 12: news.AddToSearchHistoryResponse
	(*GetSearchHistoryRequest)(nil),    // 13: news.GetSearchHistoryRequest
	(*GetSearchHistoryResponse)(nil),   // 14: news.GetSearchHistoryResponse
	(*SubscribeRequest)(nil),           // 15: news.SubscribeRequest
	(*SubscribeResponse)(nil),          // 16: news.SubscribeResponse
	(*GetSubscriptionsRequest)(nil),    // 17: news.GetSubscriptionsRequest
	(*GetSubscriptionsResponse)(nil),   // 18: news.GetSubscriptionsResponse
	(*Subscription)(nil),               // 19: news.Subscription
	(*SearchNewsRequest)(nil),          // 20: news.SearchNewsRequest
	(*SearchNewsResponse)(nil),         // 21: news.SearchNewsResponse
	(*GetTopHeadlinesRequest)(nil),     // 22: news.GetTopHeadlinesRequest
	(*GetTopHeadlinesResponse)(nil),    // 23: news.GetTopHeadlinesResponse
	(*CheckNewArticlesRequest)(nil),    // 24: news.CheckNewArticlesRequest
	(*CheckNewArticlesResponse)(nil),   // 25: news.CheckNewArticlesResponse
	(*SendNotificationRequest)(nil),    // 26: news.SendNotificationRequest
	(*SendNotificationResponse)(nil),   // 27: news.SendNotificationResponse
}
var file_news_service_proto_depIdxs = []int32{
	0,  // 0: news.SaveNewsRequest.news:type_name -> news.News
	0,  // 1: news.GetNewsByIDsResponse.news:type_name -> news.News
	0,  // 2: news.GetFavouritesResponse.news:type_name -> news.News
	19, // 3: news.GetSubscriptionsResponse.subscriptions:type_name -> news.Subscription
	0,  // 4: news.SearchNewsResponse.news:type_name -> news.News
	0,  // 5: news.GetTopHeadlinesResponse.news:type_name -> news.News
	0,  // 6: news.CheckNewArticlesResponse.new_articles:type_name -> news.News
	0,  // 7: news.SendNotificationRequest.articles:type_name -> news.News
	1,  // 8: news.SaveService.CreateUser:input_type -> news.CreateUserRequest
	3,  // 9: news.SaveService.SaveNews:input_type -> news.SaveNewsRequest
	5,  // 10: news.SaveService.GetNewsByIDs:input_type -> news.GetNewsByIDsRequest
	7,  // 11: news.SaveService.AddFavourite:input_type -> news.AddFavouriteRequest
	9,  // 12: news.SaveService.GetFavourites:input_type -> news.GetFavouritesRequest
	11, // 13: news.SaveService.AddToSearchHistory:input_type -> news.AddToSearchHistoryRequest
	13, // 14: news.SaveService.GetSearchHistory:input_type -> news.GetSearchHistoryRequest
	15, // 15: news.SaveService.Subscribe:input_type -> news.SubscribeRequest
	17, // 16: news.SaveService.GetSubscriptions:input_type -> news.GetSubscriptionsRequest
	20, // 17: news.SearchService.SearchNews:input_type -> news.SearchNewsRequest
	22, // 18: news.SearchService.GetTopHeadlines:input_type -> news.GetTopHeadlinesRequest
	24, // 19: news.SearchService.CheckNewArticles:input_type -> news.CheckNewArticlesRequest
	26, // 20: news.NotificationService.SendNotification:input_type -> news.SendNotificationRequest
	2,  // 21: news.SaveService.CreateUser:output_type -> news.CreateUserResponse
	4,  // 22: news.SaveService.SaveNews:output_type -> news.SaveNewsResponse
	6,  // 23: news.SaveService.GetNewsByIDs:output_type -> news.GetNewsByIDsResponse
	8,  // 24: news.SaveService.AddFavourite:output_type -> news.AddFavouriteResponse
	10, // 25: news.SaveService.GetFavourites:output_type -> news.GetFavouritesResponse
	12, // 26: news.SaveService.AddToSearchHistory:output_type -> news.AddToSearchHistoryResponse
	14, // 27: news.SaveService.GetSearchHistory:output_type -> news.GetSearchHistoryResponse
	16, // 28: news.SaveService.Subscribe:output_type -> news.SubscribeResponse
	18, // 29: news.SaveService.GetSubscriptions:output_type -> news.GetSubscriptionsResponse
	21, // 30: news.SearchService.SearchNews:output_type -> news.SearchNewsResponse
	23, // 31: news.SearchService.GetTopHeadlines:output_type -> news.GetTopHeadlinesResponse
	25, // 32: news.SearchService.CheckNewArticles:output_type -> news.CheckNewArticlesResponse
	27, // 33: news.NotificationService.SendNotification:output_type -> news.SendNotificationResponse
	21, // [21:34] is the sub-list for method output_type
	8,  // [8:21] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_news_service_proto_init() }
func file_news_service_proto_init() {
	if File_news_service_proto != nil {
		return
	}
	file_news_service_proto_msgTypes[20].OneofWrappers = []any{}
	file_news_service_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_news_service_proto_rawDesc), len(file_news_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_news_service_proto_goTypes,
		DependencyIndexes: file_news_service_proto_depIdxs,
		MessageInfos:      file_news_service_proto_msgTypes,
	}.Build()
	File_news_service_proto = out.File
	file_news_service_proto_goTypes = nil
	file_news_service_proto_depIdxs = nil
}
